[font]
size = 12.0

[font.normal]
family = "0xProtoNerdFontMono"
style = "Regular"

[font.bold]
family = "0xProtoNerdFontMono"
style = "Bold"

[font.italic]
family = "0xProtoNerdFontMono"
style = "Italic"

[font.bold_italic]
family = "0xProtoNerdFontMono"
style = "Bold Italic"
