# Config as of ashell v0.6.0
log_level = "warn" # debug, info, warn
outputs = "All" # "All", "Active", or a specific list of monitors like "eDP-1"
position = "Top" # "Top" or "Bottom"
enable_esc_key = true

[modules]
left = [ [  "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [ "Tray", "Clock", "Privacy", "Updates", "Settings" ] ]

[app_launcher]
app_launcher_cmd = "walker"

# clipboard_cmd = "clipvault"

[updates]
check_cmd = "dnf check-update"
update_cmd = 'alacritty -e bash -c "sudo dnf upgrade --refresh; sudo flatpak update; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "All" # All or MonitorSpecific
enable_workspace_filling = true
# max_workspaces = None # default is None
workspace_names = ["‰∏Ä","‰∫å","‰∏â","Âõõ","‰∫î","ÂÖ≠","‰∏É","ÂÖ´","‰πù","ÂçÅ",]

[window_title]
mode = "Title" # Title or Class
truncate_title_after_length = 75

[system_info]
indicators = ["Temperature"]
# indicators = ["Cpu", "Memory", "MemorySwap", { Disk = "/home" }, "IpAddress", "DownloadSpeed", "UploadSpeed", "Temperature" ]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80

[clock]
format = "%B %e, %Y, %A; %l:%M:%S %p" # August 14, 2004, Saturday; 12:00:00 PM

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"

[appearance]
font_name = "0xProtoNerdFontMono"
scale_factor = 1.0
# style = "Gradient" # sample
# opacity = 0.8 # sample
# backdrop = 0.3 # sample

# below are Tokyo Night - night configs https://malpenzibo.github.io/ashell/docs/configuration/appearance/theme#tokyo-night---night
primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"

# [[CustomModule]]
# name = "appLauncher"
# icon = "Û±óº"
# command = "walker"

# [[CustomModule]]
# name = "clipboard"
# icon = "üìã"
# command = "clipvault"
