# From https://malpenzibo.github.io/ashell/docs/configuration/modules#default-configuration
[modules]
left = [ "Workspaces" ]
center = [ "WindowTitle" ]
right = [ [ "Clock", "Privacy", "Settings" ] ]

# From https://malpenzibo.github.io/ashell/docs/configuration/modules/workspaces
[workspaces]
visibility_mode = "All"
enable_workspace_filling = true
max_workspaces = None

# From https://malpenzibo.github.io/ashell/docs/configuration/modules/window_title
[window_title]
mode = "Title"
truncate_title_after_length = 150

# From https://malpenzibo.github.io/ashell/docs/configuration/modules/system_info#default-configuration
[system_info]
indicators = [ "Cpu", "Memory", "Temperature" ]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[system_info.temperature]
warn_threshold = 60
alert_threshold = 80

# From https://malpenzibo.github.io/ashell/docs/configuration/modules/clock
[clock]
format = "%a %d %b %R"

# From https://malpenzibo.github.io/ashell/docs/configuration/modules/media_player
[media_player]
max_title_length = 100

# From https://malpenzibo.github.io/ashell/docs/configuration/modules/settings
[settings]
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"

[appearance]
# From https://malpenzibo.github.io/ashell/docs/configuration/appearance/general#scaling-factor
scale_factor = 1.0
# From https://malpenzibo.github.io/ashell/docs/configuration/appearance/general#status-bar-style
style = "Island"
